spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/bookeeper
    username: bookeeper
    password: bookeeper-dev
    driver-class-name: org.postgresql.Driver
    initialization-mode : embedded
#    schema: schema.sql
#    data: data.sql

  messages.basename: i18n.bundle

---
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:bookeeper
    username: bookeeper
    password:
    initialization-mode : always
#    schema: schema.sql
#    data: data.sql

---
spring:
  profiles:
    active: h2
