spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/bookeeper
    username: bookeeper
    password: bookeeper-dev
    driver-class-name: org.postgresql.Driver
    initialization-mode : embedded
#    schema: schema.sql
#    data: data.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  messages.basename: i18n.bundle

---
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:bookeeper
    username: bookeeper
    password:
    initialization-mode : embedded
    schema: schema.sql
    data: data.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  profiles: mongo
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb
---
spring:
  profiles:
    active: mongo
