spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/bookeeper
    username: bookeeper
    password: bookeeper-dev
    driver-class-name: org.postgresql.Driver
    initialization-mode : embedded
#    schema: schema.sql
#    data: data.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  messages.basename: i18n.bundle

---
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:bookeeper
    username: bookeeper
    password:
    initialization-mode : embedded
    schema: schema.sql
    data: data.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  profiles: mongo
  data:
    mongodb:
      host: ${mongo.host}
      port: 27017
      database: mydb
      mongock-enabled: true

---
spring:
  profiles: container
  shell:
    interactive:
      enabled: false
---
spring:
  profiles:
    active: mongo, container
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, logfile
  health:
    mongo:
      enabled: true
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always

logging:
  file:
    path: spring-logs

weather-service:
  city-id: 524901 # Moscow
  #city-id: 2950159 Berlin
  app-id: 0830b9bc178d96e61cdf65482fcd57f7
