spring:
  datasource:
    jdbc-url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  business-datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/migration-db
    driverClassName: org.postgresql.Driver
    username: migration-master
    password: migr-pass

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    mongodb:
      #uri: mongodb://localhost
      host: localhost
      port: 27017
      database: migration

  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true
